services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"  # Run as root to avoid permission issues
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./scripts:/scripts
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  mssql-setup:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    command: /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "YourStrong@Passw0rd" -d master -i /scripts/mssql_setup.sql -N -C

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prefect-server:
    image: prefecthq/prefect:3.0.0rc16-python3.12
    restart: always
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:password@postgres/prefect
    volumes:
      - prefect_data:/root/.prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - 4200:4200

  prefect-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-prefect-worker
    restart: always
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      - prefect-server
    volumes:
      - ./:/app

volumes:
  mssql-data:
  postgres-data:
  prefect_data:
