FROM prefecthq/prefect:3.0.0rc16-python3.12

# Install additional dependencies
RUN pip install pandas sqlalchemy prefect-sqlalchemy pyodbc

# Install ODBC driver for SQL Server
RUN apt-get update && apt-get install -y gnupg2 curl
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18

# Add mssql-tools18 to PATH
ENV PATH="$PATH:/opt/mssql-tools18/bin"

WORKDIR /app

COPY flows/data_transfer_flow.py .

CMD ["prefect", "worker", "start", "-p", "new-workerpool"]